

export const POSITIVE_COLOR_LIGHT = 'rgba(8,112,55,0.2)';
export const NEUTRAL_COLOR_LIGHT = 'rgba(239,194,71,0.2)';
export const NEGATIVE_COLOR_LIGHT = 'rgba(8,76,112,0.2)';
export const MIXED_COLOR_LIGHT = 'rgba(97,81,124,0.2)';
export const SENTIMENT_COLOR_LIGHT = [POSITIVE_COLOR_LIGHT, NEUTRAL_COLOR_LIGHT, NEGATIVE_COLOR_LIGHT, MIXED_COLOR_LIGHT];

export const POSITIVE_COLOR_MED = 'rgba(8,112,55,0.4)';
export const NEUTRAL_COLOR_MED = 'rgba(239,194,71,0.4)';
export const NEGATIVE_COLOR_MED = 'rgba(8,76,112,0.4)';
export const MIXED_COLOR_MED = 'rgba(97,81,124,0.4)';
export const SENTIMENT_COLOR_MED = [POSITIVE_COLOR_MED, NEUTRAL_COLOR_MED, NEGATIVE_COLOR_MED, MIXED_COLOR_MED];

export const POSITIVE_COLOR_SOLID = 'rgba(8,112,55,1)';
export const NEUTRAL_COLOR_SOLID = 'rgba(239,194,71,1)';
export const NEGATIVE_COLOR_SOLID = 'rgba(8,76,112,1)';
export const MIXED_COLOR_SOLID = 'rgba(97,81,124,1)';
export const SENTIMENT_COLOR_SOLID = [POSITIVE_COLOR_SOLID, NEUTRAL_COLOR_SOLID, NEGATIVE_COLOR_SOLID, MIXED_COLOR_SOLID];

